openapi: 3.1.0
info:
  version: 1.0.0
  title: Test Spec
  license:
    name: MIT

paths:
  /foo:
    get:
      summary: test GET route /foo
      operationId: getFoo
      security:
        - bearerAuth: []
      tags:
        - foo
      responses:
        '204':
          description: test GET route /foo
          content:
            application/json:
              schema:
                type: object
                properties:
                  foo:
                    type: string

